<center>
<img src="../../img/ods_stickers.jpg" />
    
## [mlcourse.ai](mlcourse.ai) â€“ Open Machine Learning Course 
Author: Arina Lopukhova (@erynn). Edited by [Yury Kashnitskiy](https://yorko.github.io) (@yorko). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.

<h1><center>Assignment #1. Fall 2018</center></h1>
<h2><center>Exploratory data analysis of Olympic games with Pandas</center></h2>

__There are ten questions about [120 years of Olympic history: athletes and results](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results/version/2) dataset in this task. Your task is to fill in the missing Python code and choose answers in [this web-form](https://docs.google.com/forms/d/179HYvlF_0x435CWdu2aOtR9a3flh0YCQXXNXhXaKw2M).__

Download the file `athlete_events.csv` from [Kaggle page](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results). The dataset has the following features (copied from Kaggle):

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [2]:
import pandas as pd

In [5]:
# Change the path to the dataset file if needed. 
PATH = '../../data/120-years-of-olympic-history-athletes-and-results/athlete_events.csv'

In [6]:
data = pd.read_csv(PATH)
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

__1. How old were the youngest male and female participants of the 1996 Olympics?__

- 16 and 15
- 14 and 12 
- 16 and 12
- 13 and 11

In [16]:
# You code here 
data[(data['Year']==1996) & (data['Sex']=='M')].sort_values('Age')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
87416,44326,Gwon Gyeong-Min,M,14.0,165.0,60.0,South Korea,KOR,1996 Summer,1996,Summer,Atlanta,Diving,Diving Men's Platform,NaN
170448,85647,Ng Sui,M,15.0,NaN,NaN,Hong Kong,HKG,1996 Summer,1996,Summer,Atlanta,Diving,Diving Men's Platform,NaN
139132,69887,"Keng Liat ""Alex"" Lim",M,15.0,178.0,63.0,Malaysia,MAS,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Backstroke,NaN
139133,69887,"Keng Liat ""Alex"" Lim",M,15.0,178.0,63.0,Malaysia,MAS,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Backstroke,NaN
80392,40801,Daniel A. Glomb,M,15.0,178.0,80.0,Brazil,BRA,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN
139134,69887,"Keng Liat ""Alex"" Lim",M,15.0,178.0,63.0,Malaysia,MAS,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
237790,119243,Ken Terauchi,M,15.0,170.0,68.0,Japan,JPN,1996 Summer,1996,Summer,Atlanta,Diving,Diving Men's Platform,NaN
48506,25002,Omar Dallal,M,15.0,NaN,NaN,Jordan,JOR,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 400 metres Freestyle,NaN
239728,120144,"Ping Tjin ""PJ"" Thum",M,16.0,NaN,NaN,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 200 metres Freestyle Relay,NaN
268069,134109,Denys Zavhorodniy,M,16.0,NaN,NaN,Ukraine,UKR,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Freestyle,NaN
168343,84593,Darko Naseski,M,16.0,NaN,NaN,Macedonia,MKD,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Air Rifle, 10 metres",NaN
239731,120144,"Ping Tjin ""PJ"" Thum",M,16.0,NaN,NaN,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
216946,108948,Torlarp Sethsothorn,M,16.0,NaN,NaN,Thailand,THA,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Freestyle,NaN
216948,108948,Torlarp Sethsothorn,M,16.0,NaN,NaN,Thailand,THA,1996 Summer,1996,Summer,Atlanta,Swimming,"Swimming Men's 1,500 metres Freestyle",NaN
165237,82981,Diego Mularoni,M,16.0,183.0,77.0,San Marino,SMR,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Freestyle,NaN
268070,134109,Denys Zavhorodniy,M,16.0,NaN,NaN,Ukraine,UKR,1996 Summer,1996,Summer,Atlanta,Swimming,"Swimming Men's 1,500 metres Freestyle",NaN
239892,120212,Tian Liang,M,16.0,172.0,60.0,China,CHN,1996 Summer,1996,Summer,Atlanta,Diving,Diving Men's Platform,NaN
262343,131263,Andrzej Wjs,M,16.0,184.0,73.0,Poland-2,POL,1996 Summer,1996,Summer,Atlanta,Canoeing,"Canoeing Men's Canadian Doubles, Slalom",NaN
224082,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 50 metres Freestyle,NaN
224083,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Freestyle,NaN
224084,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Freestyle,NaN
224085,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 400 metres Freestyle,NaN
224086,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 200 metres Freestyle Relay,NaN
216949,108948,Torlarp Sethsothorn,M,16.0,NaN,NaN,Thailand,THA,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
239730,120144,"Ping Tjin ""PJ"" Thum",M,16.0,NaN,NaN,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Butterfly,NaN
216947,108948,Torlarp Sethsothorn,M,16.0,NaN,NaN,Thailand,THA,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 400 metres Freestyle,NaN
224087,112557,Sng Ju Wei,M,16.0,177.0,73.0,Singapore,SGP,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
177125,89053,Ahmed Rajab Omari,M,16.0,183.0,91.0,Kenya,KEN,1996 Summer,1996,Summer,Atlanta,Boxing,Boxing Men's Heavyweight,NaN
108667,54964,Jo Gwang-Je,M,16.0,NaN,NaN,South Korea,KOR,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
108666,54964,Jo Gwang-Je,M,16.0,NaN,NaN,South Korea,KOR,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Breaststroke,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206500,103658,Ricardo Antonio Rusticucci Fernndez,M,50.0,180.0,78.0,Argentina,ARG,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Small-Bore Rifle, Three Positio...",NaN
206499,103658,Ricardo Antonio Rusticucci Fernndez,M,50.0,180.0,78.0,Argentina,ARG,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Air Rifle, 10 metres",NaN
1504,835,"Phillip Maxwell ""Phil"" Adams",M,50.0,163.0,93.0,Australia,AUS,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Free Pistol, 50 metres",NaN
1503,835,"Phillip Maxwell ""Phil"" Adams",M,50.0,163.0,93.0,Australia,AUS,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Air Pistol, 10 metres",NaN
39611,20373,"Cheng Shu Ming ""Micky""",M,50.0,170.0,66.0,Hong Kong,HKG,1996 Summer,1996,Summer,Atlanta,Shooting,Shooting Men's Trap,NaN
56439,28916,Hryhoriy Mykolaiovych Dmytrenko,M,51.0,152.0,52.0,Ukraine,UKR,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Coxed Eights,NaN
166423,83588,"Patrick Brian ""Pat"" Murray",M,51.0,181.0,85.0,Australia,AUS,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Rapid-Fire Pistol, 25 metres",NaN
68152,34817,Grard Fernandez,M,53.0,162.0,69.0,France,FRA,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Free Pistol, 50 metres",NaN
23393,12307,Herbert Blcker,M,53.0,173.0,68.0,Germany,GER,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Three-Day Event, Individual",NaN
68151,34817,Grard Fernandez,M,53.0,162.0,69.0,France,FRA,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Air Pistol, 10 metres",NaN
220572,110778,Hugo Simon,M,53.0,162.0,65.0,Austria,AUT,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Jumping, Individual",NaN
220573,110778,Hugo Simon,M,53.0,162.0,65.0,Austria,AUT,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Jumping, Team",NaN
197501,99155,Hubert Raudaschl,M,53.0,187.0,82.0,Austria,AUT,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Two Person Keelboat,NaN
263058,131631,Gyrgy Wossala,M,54.0,180.0,104.0,Hungary,HUN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN
202760,101843,Ralph Rodrguez Beauchamp,M,54.0,178.0,66.0,Puerto Rico,PUR,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Small-Bore Rifle, Prone, 50 metres",NaN
13395,7272,"Nikolaus ""Klaus"" Balkenhol",M,56.0,178.0,83.0,Germany,GER,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Dressage, Individual",NaN
13396,7272,"Nikolaus ""Klaus"" Balkenhol",M,56.0,178.0,83.0,Germany,GER,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Dressage, Team",Gold
156999,78863,Bruce Meredith,M,59.0,188.0,82.0,United States Virgin Islands,ISV,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Small-Bore Rifle, Prone, 50 metres",NaN
222025,111582,Karl Ragnar Skanker (Eriksson-),M,62.0,183.0,83.0,Sweden,SWE,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Free Pistol, 50 metres",NaN
222024,111582,Karl Ragnar Skanker (Eriksson-),M,62.0,183.0,83.0,Sweden,SWE,1996 Summer,1996,Summer,Atlanta,Shooting,"Shooting Men's Air Pistol, 10 metres",NaN
9789,5360,Jos Antonio Artecona Artze,M,63.0,175.0,87.0,Puerto Rico,PUR,1996 Summer,1996,Summer,Atlanta,Shooting,Shooting Men's Double Trap,NaN
193987,97377,Fausto Maria Puccini,M,63.0,169.0,67.0,Italy,ITA,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Dressage, Individual",NaN
193988,97377,Fausto Maria Puccini,M,63.0,169.0,67.0,Italy,ITA,1996 Summer,1996,Summer,Atlanta,Equestrianism,"Equestrianism Mixed Dressage, Team",NaN
9788,5360,Jos Antonio Artecona Artze,M,63.0,175.0,87.0,Puerto Rico,PUR,1996 Summer,1996,Summer,Atlanta,Shooting,Shooting Men's Trap,NaN
27170,14130,Grayson Hugh Bourne,M,NaN,NaN,NaN,Great Britain,GBR,1996 Summer,1996,Summer,Atlanta,Canoeing,"Canoeing Men's Kayak Doubles, 1,000 metres",NaN
119298,60395,Boureima Kimba,M,NaN,NaN,NaN,Niger,NIG,1996 Summer,1996,Summer,Atlanta,Athletics,Athletics Men's 100 metres,NaN
148866,74668,Abdou Manzo,M,NaN,NaN,NaN,Niger,NIG,1996 Summer,1996,Summer,Atlanta,Athletics,Athletics Men's Marathon,NaN
181426,91182,Raymond Anthony Papa,M,NaN,NaN,NaN,Philippines,PHI,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Freestyle,NaN
181427,91182,Raymond Anthony Papa,M,NaN,NaN,NaN,Philippines,PHI,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Backstroke,NaN
181428,91182,Raymond Anthony Papa,M,NaN,NaN,NaN,Philippines,PHI,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Backstroke,NaN

__2. What was the percentage of male gymnasts among all the male participants of the 2000 Olympics? Round the answer to the first decimal.__

*Hint:* here and further if needed drop duplicated sportsmen to count only unique ones. 

- 0.2
- 1.5 
- 2.5
- 7.7

In [62]:
# You code here 
data[(data['Year']==2000) & (data['Sex']=='M')].drop_duplicates('ID')['Sport'].value_counts(normalize=True)

Athletics            0.191062
Swimming             0.084815
Rowing               0.055176
Cycling              0.051832
Wrestling            0.047728
Sailing              0.046664
Boxing               0.046664
Football             0.040584
Shooting             0.039824
Canoeing             0.037848
Judo                 0.036024
Baseball             0.029184
Hockey               0.029032
Handball             0.026904
Weightlifting        0.024472
Water Polo           0.023256
Basketball           0.021888
Volleyball           0.021432
Fencing              0.020368
Equestrianism        0.019456
Gymnastics           0.014744
Tennis               0.014136
Badminton            0.013072
Table Tennis         0.013072
Diving               0.012160
Archery              0.009728
Taekwondo            0.008208
Triathlon            0.007904
Beach Volleyball     0.007296
Modern Pentathlon    0.003648
Trampolining         0.001824
Name: Sport, dtype: float64

__3. What are the mean and standard deviation of height for female basketball players participated in the 2000 Olympics? Round the answer to the first decimal.__

- 178.5 and 7.2
- 179.4 and 10
- 180.7 and 6.7
- 182.4 and 9.1

In [92]:
# You code here 
data[(data['Year']==2000) & (data['Sex']=='F') & (data['Sport']=='Basketball')].describe()

                  ID         Age      Height      Weight    Year
count     142.000000  142.000000  142.000000  142.000000   142.0
mean    65981.295775   26.690141  182.387324   73.464789  2000.0
std     38666.204358    4.185729    9.139462    9.002491     0.0
min       580.000000   17.000000  162.000000   58.000000  2000.0
25%     33914.250000   24.000000  175.000000   67.000000  2000.0
50%     64471.500000   27.000000  182.000000   73.000000  2000.0
75%     96557.000000   30.000000  190.000000   80.000000  2000.0
max    135105.000000   37.000000  213.000000  100.000000  2000.0

__4. Find a sportsperson participated in the 2002 Olympics, with the highest weight among other participants of the same Olympics. What sport did he or she do?__

- Judo
- Bobsleigh 
- Weightlifting
- Boxing

In [77]:
# You code here 
data[(data['Year']==2002)].sort_values('Weight', ascending=False)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
99154,50171,Emmanuel Hostache,M,26.0,190.0,123.0,France,FRA,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
129595,65246,Kevin Kuske,M,23.0,196.0,116.0,Germany-2,GER,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,Gold
270556,135315,Zsolt Zsombor,M,30.0,193.0,115.0,Hungary,HUN,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
60488,30980,Dalibor uri,M,26.0,196.0,113.0,Serbia and Montenegro,SCG,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
128125,64528,Pavel Kubina,M,24.0,196.0,113.0,Czech Republic,CZE,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
233708,117214,Michal Skora,M,28.0,196.0,112.0,Czech Republic,CZE,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
93069,47140,Beat Hefti,M,24.0,183.0,110.0,Switzerland-1,SUI,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
93068,47140,Beat Hefti,M,24.0,183.0,110.0,Switzerland-2,SUI,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,Bronze
4567,2596,Yorgo Alexandrou,M,29.0,190.0,110.0,Armenia,ARM,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
207785,104284,Franz Sagmeister,M,27.0,191.0,110.0,Germany-1,GER,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
207784,104284,Franz Sagmeister,M,27.0,191.0,110.0,Germany-2,GER,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
131234,66048,Andr Lakos,M,22.0,201.0,108.0,Austria,AUT,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
200450,100657,Scott Frederick Rider,M,24.0,188.0,108.0,Great Britain-1,GBR,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
48996,25251,Ivo Danilevi,M,31.0,188.0,107.0,Czech Republic,CZE,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
257639,129024,Winston Alexander Watts,M,34.0,182.0,107.0,Jamaica,JAM,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
139888,70239,Eric Bryan Lindros,M,28.0,193.0,107.0,Canada,CAN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold
175587,88263,Hiroaki Ohishi,M,31.0,182.0,107.0,Japan-2,JPN,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
92539,46875,Todd Dennys Hays,M,32.0,190.0,107.0,United States-1,USA,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
92540,46875,Todd Dennys Hays,M,32.0,190.0,107.0,United States-1,USA,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,Silver
48995,25251,Ivo Danilevi,M,31.0,188.0,107.0,Czech Republic-2,CZE,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
159992,80285,Boris Olegovich Mironov,M,29.0,190.0,106.0,Russia,RUS,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
134042,67493,ric Le Chanony,M,33.0,198.0,106.0,France-1,FRA,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
147361,73958,Vladimir Igorevich Malakhov,M,33.0,193.0,105.0,Russia,RUS,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
125791,63458,Aleksey Vyacheslavovich Kovalyov,M,28.0,177.0,105.0,Russia,RUS,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
22410,11801,Tahir Bisi,M,20.0,190.0,105.0,Bosnia and Herzegovina,BIH,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
197841,99339,Vuk Raenovi,M,18.0,192.0,105.0,Serbia and Montenegro,SCG,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
22412,11801,Tahir Bisi,M,20.0,190.0,105.0,Bosnia and Herzegovina,BIH,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Combined,NaN
269895,135034,Markus Zimmermann,M,37.0,191.0,105.0,Germany-1,GER,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN
269894,135034,Markus Zimmermann,M,37.0,191.0,105.0,Germany-1,GER,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,Gold
22411,11801,Tahir Bisi,M,20.0,190.0,105.0,Bosnia and Herzegovina,BIH,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100627,50885,Sarah Elizabeth Hughes,F,16.0,160.0,NaN,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Women's Singles,Gold
100867,51005,Marika Humphreys (-Baranov),F,25.0,170.0,NaN,Great Britain,GBR,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
103596,52416,Elbrus Hudsiyat Oglu Isakov,M,20.0,NaN,NaN,Azerbaijan,AZE,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
108147,54668,Norman Jeschke,M,22.0,179.0,NaN,Germany,GER,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
114751,58111,Mariana Kautz (-Patschinski),F,21.0,155.0,NaN,Germany,GER,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
119376,60435,"Arthur James ""Arturo"" Kinch Barton",M,45.0,NaN,NaN,Costa Rica,CRC,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's Sprint,NaN
119377,60435,"Arthur James ""Arturo"" Kinch Barton",M,45.0,NaN,NaN,Costa Rica,CRC,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's 10/10 kilometres Pu...,NaN
125053,63113,Vladimir Kostin,M,26.0,NaN,NaN,Kazakhstan,KAZ,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
125054,63113,Vladimir Kostin,M,26.0,NaN,NaN,Kazakhstan,KAZ,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
126440,63760,Maria Krasiltseva,F,20.0,163.0,NaN,Armenia,ARM,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
130521,65714,Nataa Laen,F,30.0,NaN,NaN,Slovenia,SLO,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Women's Sprint,NaN
130522,65714,Nataa Laen,F,30.0,NaN,NaN,Slovenia,SLO,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Women's 10 kilometres,NaN
130523,65714,Nataa Laen,F,30.0,NaN,NaN,Slovenia,SLO,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Women's 15 kilometres,NaN
130524,65714,Nataa Laen,F,30.0,NaN,NaN,Slovenia,SLO,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Women's 5/5 kilometres Pu...,NaN
130525,65714,Nataa Laen,F,30.0,NaN,NaN,Slovenia,SLO,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Women's 4 x 5 kilometres ...,NaN
133237,67067,Roberto Lauderdale Navarro,M,20.0,NaN,NaN,Mexico,MEX,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
134339,67629,Yulia Lebedeva,F,23.0,165.0,NaN,Armenia,ARM,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Women's Singles,NaN
136316,68558,Ioannis Leivaditis,M,28.0,NaN,NaN,Greece,GRE,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Two,NaN
172072,86461,"Cynthia Susan ""Cindy"" Ninos",F,29.0,NaN,NaN,Greece,GRE,2002 Winter,2002,Winter,Salt Lake City,Skeleton,Skeleton Women's Skeleton,NaN
180495,90717,Dmytro Palamarchuk,M,22.0,175.0,NaN,Ukraine-2,UKR,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
191243,96043,Nataliya Ponomaryova,F,19.0,153.0,NaN,Uzbekistan,UZB,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
206977,103876,Sergey Rylov,M,26.0,171.0,NaN,Azerbaijan,AZE,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Men's Singles,NaN
215184,108029,Tiffany Erin Scott,F,24.0,152.0,NaN,United States-2,USA,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
225173,113133,Song Li,F,20.0,NaN,NaN,China,CHN,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
225174,113133,Song Li,F,20.0,NaN,NaN,China,CHN,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Women's 1,500 metres",NaN
233264,117005,Yevgeny Sviridov,M,27.0,183.0,NaN,Uzbekistan,UZB,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN
234583,117636,David Szurman,M,20.0,187.0,NaN,Czech Republic,CZE,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
253219,126805,"Maria Margaretha Antje ""Marja"" Vis",F,25.0,NaN,NaN,Netherlands,NED,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Women's 5,000 metres",NaN
268939,134557,Zhang Weina,F,23.0,166.0,NaN,China,CHN,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
270190,135168,Artyom Znachkov,M,23.0,182.0,NaN,Armenia,ARM,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Mixed Pairs,NaN

__5. How many times did Pawe Abratkiewicz participate in the Olympics held in different years?__

- 0
- 1 
- 2
- 3

In [86]:
# You code here 
data[(data['Name']=='Pawe Abratkiewicz')].groupby('Year').count()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
Year,,,,,,,,,,,,,,
1992,2,2,2,2,2,2,2,2,2,2,2,2,2,0
1998,2,2,2,2,2,2,2,2,2,2,2,2,2,0
2002,2,2,2,2,2,2,2,2,2,2,2,2,2,0

__6. How many silver medals in tennis did Australia win at the 2000 Olympics?__

- 0
- 1 
- 2 
- 3

In [93]:
# You code here 
data[(data['NOC']=='AUS') & (data['Year']==2000) & (data['Sport']=='Tennis') & (data['Medal']=='Silver')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
262820,131504,Todd Andrew Woodbridge,M,29.0,178.0,75.0,Australia,AUS,2000 Summer,2000,Summer,Sydney,Tennis,Tennis Men's Doubles,Silver
262831,131511,Mark Raymond Woodforde,M,34.0,183.0,80.0,Australia,AUS,2000 Summer,2000,Summer,Sydney,Tennis,Tennis Men's Doubles,Silver

__7. Is it true that Switzerland won fewer medals than Serbia at the 2016 Olympics? Do not consider NaN values in _Medal_ column.__ 

- Yes 
- No

In [166]:
# You code here 
data[(data['Year']==2016) & ((data['NOC']=='SUI') | (data['NOC']=='SRB'))].groupby('NOC').count()

,ID,Name,Sex,Age,Height,Weight,Team,Games,Year,Season,City,Sport,Event,Medal
NOC,,,,,,,,,,,,,,
SRB,127,127,127,127,127,127,127,127,127,127,127,127,127,54
SUI,152,152,152,152,152,152,152,152,152,152,152,152,152,11

__8. What age category did the fewest and the most participants of the 2014 Olympics belong to?__
- [45-55] and [25-35) correspondingly
- [45-55] and [15-25) correspondingly
- [35-45] and [25-35) correspondingly
- [45-55] and [35-45) correspondingly

In [143]:
# You code here 
data[(data['Year']==2014)]['Age'].value_counts()

24.0    420
23.0    396
25.0    395
26.0    384
28.0    376
27.0    363
22.0    361
29.0    282
21.0    280
30.0    242
20.0    206
31.0    201
19.0    142
32.0    142
33.0    135
18.0    130
35.0     82
34.0     74
36.0     70
17.0     58
37.0     30
38.0     25
16.0     24
40.0     18
39.0     14
41.0     14
15.0     10
42.0      6
43.0      3
44.0      3
45.0      1
55.0      1
47.0      1
46.0      1
48.0      1
Name: Age, dtype: int64

__9. Is it true that there were Summer Olympics held in Lake Placid? Is it true that there were Winter Olympics held in Sankt Moritz?__

- Yes, Yes
- Yes, No
- No, Yes 
- No, No

In [163]:
# You code here 
data[(data['City']=='Sankt Moritz')]['Season'].drop_duplicates()

935    Winter
Name: Season, dtype: object

__10. What is the absolute difference between the number of unique sports at the 1995 Olympics and 2016 Olympics?__

- 16
- 24
- 26
- 34

In [160]:
# You code here 
data[(data['Year']==2016)]['Sport'].drop_duplicates().count()

34